---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mynetcoremicroservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mynetcoremicroservice
    spec:
      containers:
      - name: mynetcoremicroservice
        image: tribun/mynetcoremicroservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
---
apiVersion: v1
kind: Service
metadata:
  name: mynetcoremicroservice
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: mynetcoremicroservice